name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v5

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/src/**'
              - 'frontend/tests/**'
            backend:
              - 'backend/src/**'
              - 'backend/tests/**'

  frontend-tests:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test

  backend-tests:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: smartorder_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip" # Attiva il caching automatico
          cache-dependency-path: "backend/requirements.txt"
      - name: Installazione dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Attendi PostrgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo 'Waiting for postgres'
            sleep 2
          done

      - name: Analisi statica
        run: mypy src

      - name: Analisi Dinamica (pytest)
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/smartorder_test
        run: pytest

  ci-result:
    name: CI Result
    needs: [frontend-tests, backend-tests]
    if: always() # Viene eseguito anche se i test sono skipped
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          # Se uno dei job è fallito, fallisce anche questo
          if [[ "${{ needs.frontend-tests.result }}" == "failure" || "${{ needs.backend-tests.result }}" == "failure" ]]; then
            exit 1
          fi
          echo "Tutto passato o saltato correttamente."
